# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: gaur-avvv
          template: classic
          base: ""
          config_octicon: yes
          config_timezone: Asia/Calcutta
          config_twemoji: yes
          plugin_fortune: yes
          plugin_nightscout: yes
          plugin_nightscout_datapoints: 12
          plugin_nightscout_highalert: 180
          plugin_nightscout_lowalert: 80
          plugin_nightscout_urgenthighalert: 250
          plugin_nightscout_urgentlowalert: 50
          plugin_nightscout_url: https://example.herokuapp.com
          plugin_poopmap: yes
          plugin_poopmap_days: 7
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_mode: image
          plugin_screenshot_selector: body
          plugin_screenshot_title: Screenshot
          plugin_screenshot_viewport: {
  "width": 1280,
  "height": 1280
}

          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          plugin_skyline_settings: {
  "url": "https://skyline.github.com/${login}/${year}",
  "ready": "[...document.querySelectorAll('span')].map(span => span.innerText).includes('Share on Twitter')",
  "wait": 1,
  "hide": "button, footer, a"
}

          plugin_skyline_year: 20
          plugin_splatoon: yes
          plugin_splatoon_salmon_limit: 1
          plugin_splatoon_sections: player, versus, salmon-run
          plugin_splatoon_source: splatnet
          plugin_splatoon_versus_limit: 1
